# Write a program that calculates the circumference of a wheel.
# The formula is C=2πr, where π is the value 3.14 and r is the radius of the circle.

# To take this a step further, let the radius of the circle
# be a random integer generated by the random module.
import random
def circ_calc():
    PI = 3.14
    radius = random.randint(1,4)
    c = 2*(PI*radius)
    print('-'*10)
    print('\n')
    print(f"The circumference of the wheel is{c}")
circ_calc()
